name: MixerMDM
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsanitizer=12.1.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.3.2
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - aitviewer==1.13.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - clip==1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftfy==6.3.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glcontext==3.0.0
      - idna==3.10
      - imageio==2.36.0
      - imgui==2.0.0
      - importlib-metadata==8.5.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - keopscore==2.2.3
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.5
      - moderngl==5.11.1
      - moderngl-window==2.4.6
      - mpmath==1.3.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - networkx==3.4.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-contrib-python-headless==4.10.0.84
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - pybind11==2.13.6
      - pyglet==2.0.18
      - pygments==2.18.0
      - pykeops==2.2.3
      - pyparsing==3.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
      - pyrr==0.10.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.2
      - roma==1.5.0
      - scikit-image==0.24.0
      - scikit-video==1.1.11
      - scipy==1.14.1
      - sentry-sdk==2.16.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - smplx==0.1.28
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.5.0
      - tifffile==2024.9.20
      - tomli==2.0.2
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchmetrics==1.4.3
      - torchvision==0.19.1
      - tqdm==4.66.5
      - trimesh==3.23.5
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - usd-core==24.8
      - wandb==0.18.3
      - wcwidth==0.2.13
      - websockets==13.1
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.15.2
      - zipp==3.20.2
