NAME: MixerMDM

GENERATOR:
  NUM_LAYERS: 4
  NUM_HEADS: 8
  DROPOUT: 0.1
  INPUT_DIM: 262
  LATENT_DIM: 512
  FF_SIZE: 1024

DISCRIMINATOR:
  NUM_LAYERS: 2
  NUM_HEADS: 4
  DROPOUT: 0.1
  INPUT_DIM: 262
  LATENT_DIM: 256
  FF_SIZE: 512

ACTIVATION: gelu
CHECKPOINT: checkpoints/MixerMDM.ckpt

DIFFUSION_STEPS: 1000
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: false

TEXT_ENCODER: clip
T_BAR: 700

CONTROL: text
STRATEGY: ddim50

MODEL1: configs/models/individual.yaml
MODEL2: configs/models/in2IN.yaml

CFG_WEIGHT: 3.5
MIXING_MODE: 4
FORCE_INFLUENCE_VAL: None