GENERAL:
  EXP_NAME: "in2in-in2in-ST"
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-5
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 64
  EPOCH: 300
  STEP: 1000000
  LOG_STEPS: 25
  SAVE_EPOCH: 25
  RESUME: 
  NUM_WORKERS: 4
  MODE: finetune
  LAST_EPOCH: 0
  LAST_ITER: 0

  ONLY_DISCRIMINATOR: False
  INDIVIDUAL_LOSS_FACTOR: 1
  INTERACTION_LOSS_FACTOR: 2

  DISCRIMINATOR_STEPS: 1
  GRAD_ACC_STEPS: 2
  LOSS_L1: 0.1
